import type { Metadata } from 'next'
import { Inter as FontSans, Space_Grotesk as FontTitle } from 'next/font/google'
import '@/styles/globals.css'
import AppBar from './components/app-bar'
import { auth } from './api/auth/[...nextauth]/auth'
import Provider from './Provider'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Analytics } from '@vercel/analytics/react'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' })
const fontTitle = FontTitle({ subsets: ['latin'], variable: '--font-title', weight: '700' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth()

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable, fontTitle.variable)}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Provider session={session}>
            <AppBar className="fixed w-full" />
            <div className="min-h-screen">
              {session ? (
                children
              ) : (
                <div className="flex text-center justify-center h-screen items-center">Unauthorized</div>
              )}
              <SpeedInsights />
              <Analytics />
            </div>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
